// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.1 (Debug Build)
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module SubS_1080_1920_16_unsigned_char_16_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_rows_V_read,
        src_cols_V_read,
        src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read,
        src_data_stream_1_V_dout,
        src_data_stream_1_V_empty_n,
        src_data_stream_1_V_read,
        src_data_stream_2_V_dout,
        src_data_stream_2_V_empty_n,
        src_data_stream_2_V_read,
        dst_rows_V_read,
        dst_cols_V_read,
        dst_data_stream_0_V_din,
        dst_data_stream_0_V_full_n,
        dst_data_stream_0_V_write,
        dst_data_stream_1_V_din,
        dst_data_stream_1_V_full_n,
        dst_data_stream_1_V_write,
        dst_data_stream_2_V_din,
        dst_data_stream_2_V_full_n,
        dst_data_stream_2_V_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] src_rows_V_read;
input  [11:0] src_cols_V_read;
input  [7:0] src_data_stream_0_V_dout;
input   src_data_stream_0_V_empty_n;
output   src_data_stream_0_V_read;
input  [7:0] src_data_stream_1_V_dout;
input   src_data_stream_1_V_empty_n;
output   src_data_stream_1_V_read;
input  [7:0] src_data_stream_2_V_dout;
input   src_data_stream_2_V_empty_n;
output   src_data_stream_2_V_read;
input  [11:0] dst_rows_V_read;
input  [11:0] dst_cols_V_read;
output  [7:0] dst_data_stream_0_V_din;
input   dst_data_stream_0_V_full_n;
output   dst_data_stream_0_V_write;
output  [7:0] dst_data_stream_1_V_din;
input   dst_data_stream_1_V_full_n;
output   dst_data_stream_1_V_write;
output  [7:0] dst_data_stream_2_V_din;
input   dst_data_stream_2_V_full_n;
output   dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src_data_stream_0_V_read;
reg src_data_stream_1_V_read;
reg src_data_stream_2_V_read;
reg dst_data_stream_0_V_write;
reg dst_data_stream_1_V_write;
reg dst_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
reg   [1:0] ap_CS_fsm = 2'b00;
reg    ap_sig_bdd_56;
wire   [1:0] indvarinc_fu_127_p2;
reg   [1:0] scl_val_buf_address0;
reg    scl_val_buf_ce0;
reg    scl_val_buf_we0;
wire   [5:0] scl_val_buf_d0;
wire   [5:0] scl_val_buf_q0;
wire   [1:0] scl_val_buf_address1;
reg    scl_val_buf_ce1;
wire   [5:0] scl_val_buf_q1;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_start;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_done;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_idle;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_ready;
wire   [7:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_0_V_dout;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_0_V_empty_n;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_0_V_read;
wire   [7:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_1_V_dout;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_1_V_empty_n;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_1_V_read;
wire   [7:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_2_V_dout;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_2_V_empty_n;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_2_V_read;
wire   [1:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_address0;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_ce0;
wire   [5:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_q0;
wire   [1:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_address1;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_ce1;
wire   [5:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_q1;
wire   [11:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_rows_V_read;
wire   [11:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_cols_V_read;
wire   [7:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_0_V_din;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_0_V_full_n;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_0_V_write;
wire   [7:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_1_V_din;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_1_V_full_n;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_1_V_write;
wire   [7:0] grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_2_V_din;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_2_V_full_n;
wire    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_2_V_write;
reg   [1:0] invdar_reg_96;
wire   [0:0] exitcond3_fu_138_p2;
reg    grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_start_ap_start_reg = 1'b0;
wire   [63:0] tmp_fu_133_p1;
reg   [1:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 2'b00;
parameter    ap_ST_st2_fsm_1 = 2'b1;
parameter    ap_ST_st3_fsm_2 = 2'b10;
parameter    ap_ST_st4_fsm_3 = 2'b11;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv6_32 = 6'b110010;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_true = 1'b1;


SubS_1080_1920_16_unsigned_char_16_s_scl_val_buf #(
    .DataWidth( 6 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
scl_val_buf_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( scl_val_buf_address0 ),
    .ce0( scl_val_buf_ce0 ),
    .we0( scl_val_buf_we0 ),
    .d0( scl_val_buf_d0 ),
    .q0( scl_val_buf_q0 ),
    .address1( scl_val_buf_address1 ),
    .ce1( scl_val_buf_ce1 ),
    .q1( scl_val_buf_q1 )
);

arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_start ),
    .ap_done( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_done ),
    .ap_idle( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_idle ),
    .ap_ready( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_ready ),
    .src_data_stream_0_V_dout( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_0_V_dout ),
    .src_data_stream_0_V_empty_n( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_0_V_empty_n ),
    .src_data_stream_0_V_read( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_0_V_read ),
    .src_data_stream_1_V_dout( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_1_V_dout ),
    .src_data_stream_1_V_empty_n( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_1_V_empty_n ),
    .src_data_stream_1_V_read( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_1_V_read ),
    .src_data_stream_2_V_dout( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_2_V_dout ),
    .src_data_stream_2_V_empty_n( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_2_V_empty_n ),
    .src_data_stream_2_V_read( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_2_V_read ),
    .scl_val_address0( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_address0 ),
    .scl_val_ce0( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_ce0 ),
    .scl_val_q0( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_q0 ),
    .scl_val_address1( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_address1 ),
    .scl_val_ce1( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_ce1 ),
    .scl_val_q1( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_q1 ),
    .dst_rows_V_read( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_rows_V_read ),
    .dst_cols_V_read( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_cols_V_read ),
    .dst_data_stream_0_V_din( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_0_V_din ),
    .dst_data_stream_0_V_full_n( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_0_V_full_n ),
    .dst_data_stream_0_V_write( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_0_V_write ),
    .dst_data_stream_1_V_din( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_1_V_din ),
    .dst_data_stream_1_V_full_n( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_1_V_full_n ),
    .dst_data_stream_1_V_write( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_1_V_write ),
    .dst_data_stream_2_V_din( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_2_V_din ),
    .dst_data_stream_2_V_full_n( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_2_V_full_n ),
    .dst_data_stream_2_V_write( grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_2_V_write )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_done))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
            grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_ready)) begin
            grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond3_fu_138_p2 == ap_const_lv1_0))) begin
        invdar_reg_96 <= indvarinc_fu_127_p2;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_56)) begin
        invdar_reg_96 <= ap_const_lv2_0;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_CS_fsm or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_done)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_done)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_done)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_done))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// dst_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_0_V_write)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st4_fsm_3 == ap_CS_fsm))) begin
        dst_data_stream_0_V_write = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_0_V_write;
    end else begin
        dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// dst_data_stream_1_V_write assign process. ///
always @ (ap_CS_fsm or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_1_V_write)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st4_fsm_3 == ap_CS_fsm))) begin
        dst_data_stream_1_V_write = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_1_V_write;
    end else begin
        dst_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// dst_data_stream_2_V_write assign process. ///
always @ (ap_CS_fsm or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_2_V_write)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st4_fsm_3 == ap_CS_fsm))) begin
        dst_data_stream_2_V_write = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_2_V_write;
    end else begin
        dst_data_stream_2_V_write = ap_const_logic_0;
    end
end

/// scl_val_buf_address0 assign process. ///
always @ (ap_CS_fsm or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_address0 or tmp_fu_133_p1)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        scl_val_buf_address0 = tmp_fu_133_p1;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        scl_val_buf_address0 = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_address0;
    end else begin
        scl_val_buf_address0 = tmp_fu_133_p1;
    end
end

/// scl_val_buf_ce0 assign process. ///
always @ (ap_CS_fsm or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_ce0)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        scl_val_buf_ce0 = ap_const_logic_1;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        scl_val_buf_ce0 = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_ce0;
    end else begin
        scl_val_buf_ce0 = ap_const_logic_0;
    end
end

/// scl_val_buf_ce1 assign process. ///
always @ (ap_CS_fsm or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_ce1)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        scl_val_buf_ce1 = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_ce1;
    end else begin
        scl_val_buf_ce1 = ap_const_logic_0;
    end
end

/// scl_val_buf_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        scl_val_buf_we0 = ap_const_logic_1;
    end else begin
        scl_val_buf_we0 = ap_const_logic_0;
    end
end

/// src_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_0_V_read)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st4_fsm_3 == ap_CS_fsm))) begin
        src_data_stream_0_V_read = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_0_V_read;
    end else begin
        src_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// src_data_stream_1_V_read assign process. ///
always @ (ap_CS_fsm or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_1_V_read)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st4_fsm_3 == ap_CS_fsm))) begin
        src_data_stream_1_V_read = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_1_V_read;
    end else begin
        src_data_stream_1_V_read = ap_const_logic_0;
    end
end

/// src_data_stream_2_V_read assign process. ///
always @ (ap_CS_fsm or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_2_V_read)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st4_fsm_3 == ap_CS_fsm))) begin
        src_data_stream_2_V_read = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_2_V_read;
    end else begin
        src_data_stream_2_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_56 or grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_done or exitcond3_fu_138_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~ap_sig_bdd_56) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(exitcond3_fu_138_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        ap_ST_st3_fsm_2 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
        ap_ST_st4_fsm_3 : 
            if (~(ap_const_logic_0 == grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_56 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_56 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end
assign dst_data_stream_0_V_din = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_0_V_din;
assign dst_data_stream_1_V_din = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_1_V_din;
assign dst_data_stream_2_V_din = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_2_V_din;
assign exitcond3_fu_138_p2 = (invdar_reg_96 == ap_const_lv2_2? 1'b1: 1'b0);
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_start = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_ap_start_ap_start_reg;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_cols_V_read = dst_cols_V_read;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_0_V_full_n = dst_data_stream_0_V_full_n;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_1_V_full_n = dst_data_stream_1_V_full_n;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_data_stream_2_V_full_n = dst_data_stream_2_V_full_n;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_dst_rows_V_read = dst_rows_V_read;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_q0 = scl_val_buf_q0;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_q1 = scl_val_buf_q1;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_0_V_dout = src_data_stream_0_V_dout;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_0_V_empty_n = src_data_stream_0_V_empty_n;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_1_V_dout = src_data_stream_1_V_dout;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_1_V_empty_n = src_data_stream_1_V_empty_n;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_2_V_dout = src_data_stream_2_V_dout;
assign grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_src_data_stream_2_V_empty_n = src_data_stream_2_V_empty_n;
assign indvarinc_fu_127_p2 = (invdar_reg_96 + ap_const_lv2_1);
assign scl_val_buf_address1 = grp_arithm_pro_kernel_sub_1080_1920_16_unsigned_char_16_int_s_fu_108_scl_val_address1;
assign scl_val_buf_d0 = ap_const_lv6_32;
assign tmp_fu_133_p1 = $unsigned(invdar_reg_96);


endmodule //SubS_1080_1920_16_unsigned_char_16_s

