// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.1 (Debug Build)
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Erode_16_16_1080_1920_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
reg   [2:0] ap_CS_fsm = 3'b000;
reg    ap_sig_bdd_57;
wire   [1:0] i_2_fu_466_p2;
reg   [1:0] i_2_reg_1068;
wire   [0:0] sel_tmp38_i_fu_472_p2;
reg   [0:0] sel_tmp38_i_reg_1073;
wire   [0:0] exitcond_fu_460_p2;
wire   [0:0] sel_tmp47_i_fu_490_p2;
reg   [0:0] sel_tmp47_i_reg_1084;
wire   [0:0] sel_tmp50_i_fu_496_p2;
reg   [0:0] sel_tmp50_i_reg_1092;
wire   [1:0] indvar_next1_i_fu_508_p2;
reg   [1:0] indvar_next1_i_reg_1103;
wire   [0:0] tmp1_i_fu_542_p2;
reg   [0:0] tmp1_i_reg_1108;
wire   [0:0] exitcond7_fu_502_p2;
wire   [0:0] sel_tmp59_i_fu_548_p2;
reg   [0:0] sel_tmp59_i_reg_1113;
wire   [0:0] or_cond11_i_fu_583_p2;
reg   [0:0] or_cond11_i_reg_1120;
wire   [7:0] result_val13_5_i_fu_597_p3;
reg   [7:0] result_val13_5_i_reg_1129;
wire   [7:0] result_val26_5_i_fu_605_p3;
reg   [7:0] result_val26_5_i_reg_1134;
wire   [7:0] newSel39_i_fu_621_p3;
reg   [7:0] newSel39_i_reg_1139;
wire   [7:0] newSel42_i_fu_645_p3;
reg   [7:0] newSel42_i_reg_1144;
wire   [7:0] newSel29_i_fu_704_p3;
wire   [7:0] newSel31_i_fu_720_p3;
wire   [7:0] newSel34_i_fu_743_p3;
wire   [7:0] newSel37_i_fu_766_p3;
wire   [7:0] newSel43_i_fu_773_p3;
wire   [31:0] indvar_next_i_fu_787_p2;
reg   [31:0] indvar_next_i_reg_1177;
wire   [0:0] sel_tmp85_i_fu_837_p2;
reg   [0:0] sel_tmp85_i_reg_1182;
wire   [0:0] exitcond5_i_fu_781_p2;
wire   [0:0] sel_tmp87_i_fu_842_p2;
reg   [0:0] sel_tmp87_i_reg_1188;
wire   [0:0] or_cond38_i_fu_875_p2;
reg   [0:0] or_cond38_i_reg_1193;
wire   [0:0] or_cond40_i_fu_880_p2;
reg   [0:0] or_cond40_i_reg_1200;
wire   [0:0] or_cond41_i_fu_886_p2;
reg   [0:0] or_cond41_i_reg_1208;
wire   [7:0] result_val13_1_i_fu_900_p3;
reg   [7:0] result_val13_1_i_reg_1213;
wire   [7:0] newSel49_i_fu_916_p3;
reg   [7:0] newSel49_i_reg_1218;
wire   [7:0] result_val26_1_i_fu_924_p3;
reg   [7:0] result_val26_1_i_reg_1223;
wire   [7:0] newSel57_i_fu_940_p3;
reg   [7:0] newSel57_i_reg_1228;
wire   [7:0] newSel60_i_fu_964_p3;
reg   [7:0] newSel60_i_reg_1233;
wire   [7:0] newSel47_i_fu_997_p3;
wire   [7:0] newSel52_i_fu_1019_p3;
wire   [7:0] newSel55_i_fu_1040_p3;
wire   [7:0] newSel61_i_fu_1047_p3;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_idle;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_ready;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_dout;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_empty_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_dout;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_empty_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_dout;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_empty_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_din;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_full_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_din;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_full_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_din;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_full_n;
wire    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_0_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_1_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_2_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_0_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_1_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_2_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_0_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_1_read;
wire   [7:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_2_read;
wire   [11:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_rows;
wire   [11:0] grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_cols;
reg   [7:0] temp_kernel_val_0_2_reg_70;
reg   [7:0] temp_kernel_val_1_0_reg_82;
reg   [7:0] temp_kernel_val_1_1_reg_94;
reg   [7:0] temp_kernel_val_0_1_reg_106;
reg   [7:0] temp_kernel_val_1_2_reg_118;
reg   [7:0] temp_kernel_val_2_0_reg_130;
reg   [7:0] temp_kernel_val_0_0_reg_142;
reg   [7:0] temp_kernel_val_2_1_reg_154;
reg   [7:0] temp_kernel_val_2_2_reg_166;
reg   [1:0] i_reg_178;
reg   [7:0] result_val2_6_i_reg_190;
reg   [7:0] result_val13_6_i_reg_201;
reg   [7:0] result_val14_6_i_reg_212;
reg   [7:0] result_val16_6_i_reg_223;
reg   [7:0] result_val1520_6_i_reg_234;
reg   [7:0] result_val26_6_i_reg_245;
reg   [7:0] result_val_6_i_reg_256;
reg   [7:0] result_val27_6_i_reg_267;
reg   [7:0] result_val28_6_i_reg_278;
reg   [1:0] j_reg_289;
reg   [7:0] result_val2_2_i_reg_300;
reg   [7:0] result_val13_2_i_reg_312;
reg   [7:0] result_val14_2_i_reg_324;
reg   [7:0] result_val16_2_i_reg_336;
reg   [7:0] result_val1520_2_i_reg_348;
reg   [7:0] result_val26_2_i_reg_360;
reg   [7:0] result_val_2_i_reg_372;
reg   [7:0] result_val27_2_i_reg_384;
reg   [7:0] result_val28_2_i_reg_396;
reg   [31:0] indvar_i_reg_408;
reg    grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg = 1'b0;
wire   [0:0] sel_tmp45_i_fu_478_p2;
wire   [0:0] sel_tmp46_i_fu_484_p2;
wire   [0:0] sel_tmp39_i_fu_514_p2;
wire   [0:0] sel_tmp53_i_fu_530_p2;
wire   [0:0] sel_tmp55_i_fu_536_p2;
wire   [1:0] tmp_62_i_fu_559_p2;
wire   [0:0] sel_tmp48_i_fu_525_p2;
wire   [0:0] sel_tmp40_i_fu_520_p2;
wire   [0:0] tmp_63_i_fu_565_p2;
wire   [0:0] sel_tmp62_i_fu_554_p2;
wire   [0:0] or_cond_i_fu_571_p2;
wire   [0:0] or_cond8_i_fu_577_p2;
wire   [7:0] sel_tmp63_i_fu_589_p3;
wire   [7:0] newSel38_i_fu_613_p3;
wire   [7:0] newSel40_i_fu_629_p3;
wire   [7:0] newSel41_i_fu_637_p3;
wire   [0:0] tmp_fu_661_p2;
wire   [0:0] sel_tmp_i_fu_653_p2;
wire   [0:0] or_cond9_i_fu_665_p2;
wire   [7:0] newSel_i_fu_670_p3;
wire   [0:0] grp_fu_456_p2;
wire   [7:0] newSel27_i_fu_678_p3;
wire   [0:0] or_cond12_i_fu_686_p2;
wire   [0:0] or_cond13_i_fu_699_p2;
wire   [7:0] newSel28_i_fu_692_p3;
wire   [0:0] sel_tmp61_i_fu_657_p2;
wire   [7:0] newSel30_i_fu_712_p3;
wire   [7:0] newSel32_i_fu_727_p3;
wire   [7:0] newSel33_i_fu_735_p3;
wire   [7:0] newSel35_i_fu_750_p3;
wire   [7:0] newSel36_i_fu_758_p3;
wire   [1:0] tmp_133_fu_793_p1;
wire   [0:0] sel_tmp73_i_fu_797_p2;
wire   [0:0] sel_tmp81_i_fu_813_p2;
wire   [0:0] sel_tmp82_i_fu_819_p2;
wire   [0:0] sel_tmp84_i_fu_831_p2;
wire   [0:0] sel_tmp78_i_fu_808_p2;
wire   [0:0] sel_tmp74_i_fu_803_p2;
wire   [0:0] sel_tmp89_i_fu_852_p2;
wire   [0:0] sel_tmp88_i_fu_847_p2;
wire   [0:0] tmp29_i_fu_825_p2;
wire   [0:0] tmp3_fu_869_p2;
wire   [0:0] or_cond36_i_fu_857_p2;
wire   [0:0] or_cond37_i_fu_863_p2;
wire   [7:0] sel_tmp90_i_fu_892_p3;
wire   [7:0] newSel48_i_fu_908_p3;
wire   [7:0] newSel56_i_fu_932_p3;
wire   [7:0] newSel58_i_fu_948_p3;
wire   [7:0] newSel59_i_fu_956_p3;
wire   [7:0] newSel44_i_fu_972_p3;
wire   [7:0] newSel45_i_fu_979_p3;
wire   [0:0] or_cond42_i_fu_993_p2;
wire   [7:0] newSel46_i_fu_986_p3;
wire   [7:0] newSel50_i_fu_1005_p3;
wire   [7:0] newSel51_i_fu_1012_p3;
wire   [7:0] newSel53_i_fu_1026_p3;
wire   [7:0] newSel54_i_fu_1033_p3;
reg   [2:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b000;
parameter    ap_ST_st2_fsm_1 = 3'b1;
parameter    ap_ST_st3_fsm_2 = 3'b10;
parameter    ap_ST_st4_fsm_3 = 3'b11;
parameter    ap_ST_st5_fsm_4 = 3'b100;
parameter    ap_ST_st6_fsm_5 = 3'b101;
parameter    ap_ST_st7_fsm_6 = 3'b110;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_true = 1'b1;


filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start ),
    .ap_done( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done ),
    .ap_idle( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_idle ),
    .ap_ready( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_ready ),
    .p_src_data_stream_0_V_dout( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_dout ),
    .p_src_data_stream_0_V_empty_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_empty_n ),
    .p_src_data_stream_0_V_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read ),
    .p_src_data_stream_1_V_dout( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_dout ),
    .p_src_data_stream_1_V_empty_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_empty_n ),
    .p_src_data_stream_1_V_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read ),
    .p_src_data_stream_2_V_dout( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_dout ),
    .p_src_data_stream_2_V_empty_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_empty_n ),
    .p_src_data_stream_2_V_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read ),
    .p_dst_data_stream_0_V_din( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_din ),
    .p_dst_data_stream_0_V_full_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_full_n ),
    .p_dst_data_stream_0_V_write( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write ),
    .p_dst_data_stream_1_V_din( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_din ),
    .p_dst_data_stream_1_V_full_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_full_n ),
    .p_dst_data_stream_1_V_write( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write ),
    .p_dst_data_stream_2_V_din( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_din ),
    .p_dst_data_stream_2_V_full_n( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_full_n ),
    .p_dst_data_stream_2_V_write( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write ),
    .kernel_val_0_0_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_0_read ),
    .kernel_val_0_1_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_1_read ),
    .kernel_val_0_2_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_2_read ),
    .kernel_val_1_0_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_0_read ),
    .kernel_val_1_1_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_1_read ),
    .kernel_val_1_2_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_2_read ),
    .kernel_val_2_0_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_0_read ),
    .kernel_val_2_1_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_1_read ),
    .kernel_val_2_2_read( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_2_read ),
    .rows( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_rows ),
    .cols( grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_cols )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_ST_st7_fsm_6 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond_fu_460_p2 == ap_const_lv1_0))) begin
            grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_ready)) begin
            grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_2_reg_1068 <= i_2_fu_466_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        i_reg_178 <= i_2_reg_1068;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_57)) begin
        i_reg_178 <= ap_const_lv2_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        indvar_i_reg_408 <= ap_const_lv32_0;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        indvar_i_reg_408 <= indvar_next_i_reg_1177;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        indvar_next1_i_reg_1103 <= indvar_next1_i_fu_508_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        indvar_next_i_reg_1177 <= indvar_next_i_fu_787_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        j_reg_289 <= ap_const_lv2_0;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        j_reg_289 <= indvar_next1_i_reg_1103;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        newSel39_i_reg_1139 <= newSel39_i_fu_621_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        newSel42_i_reg_1144 <= newSel42_i_fu_645_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        newSel49_i_reg_1218 <= newSel49_i_fu_916_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        newSel57_i_reg_1228 <= newSel57_i_fu_940_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        newSel60_i_reg_1233 <= newSel60_i_fu_964_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        or_cond11_i_reg_1120 <= or_cond11_i_fu_583_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        or_cond38_i_reg_1193 <= or_cond38_i_fu_875_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        or_cond40_i_reg_1200 <= or_cond40_i_fu_880_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        or_cond41_i_reg_1208 <= or_cond41_i_fu_886_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        result_val13_1_i_reg_1213 <= result_val13_1_i_fu_900_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val13_2_i_reg_312 <= result_val13_6_i_reg_201;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val13_2_i_reg_312 <= result_val13_1_i_reg_1213;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val13_5_i_reg_1129 <= result_val13_5_i_fu_597_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val13_6_i_reg_201 <= temp_kernel_val_1_0_reg_82;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val13_6_i_reg_201 <= result_val13_5_i_reg_1129;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val14_2_i_reg_324 <= result_val14_6_i_reg_212;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val14_2_i_reg_324 <= newSel49_i_reg_1218;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val14_6_i_reg_212 <= temp_kernel_val_1_1_reg_94;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val14_6_i_reg_212 <= newSel31_i_fu_720_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val1520_2_i_reg_348 <= result_val1520_6_i_reg_234;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val1520_2_i_reg_348 <= newSel55_i_fu_1040_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val1520_6_i_reg_234 <= temp_kernel_val_1_2_reg_118;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val1520_6_i_reg_234 <= newSel37_i_fu_766_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val16_2_i_reg_336 <= result_val16_6_i_reg_223;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val16_2_i_reg_336 <= newSel52_i_fu_1019_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val16_6_i_reg_223 <= temp_kernel_val_0_1_reg_106;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val16_6_i_reg_223 <= newSel34_i_fu_743_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        result_val26_1_i_reg_1223 <= result_val26_1_i_fu_924_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val26_2_i_reg_360 <= result_val26_6_i_reg_245;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val26_2_i_reg_360 <= result_val26_1_i_reg_1223;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val26_5_i_reg_1134 <= result_val26_5_i_fu_605_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val26_6_i_reg_245 <= temp_kernel_val_2_0_reg_130;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val26_6_i_reg_245 <= result_val26_5_i_reg_1134;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val27_2_i_reg_384 <= result_val27_6_i_reg_267;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val27_2_i_reg_384 <= newSel60_i_reg_1233;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val27_6_i_reg_267 <= temp_kernel_val_2_1_reg_154;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val27_6_i_reg_267 <= newSel42_i_reg_1144;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val28_2_i_reg_396 <= result_val28_6_i_reg_278;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val28_2_i_reg_396 <= newSel61_i_fu_1047_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val28_6_i_reg_278 <= temp_kernel_val_2_2_reg_166;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val28_6_i_reg_278 <= newSel43_i_fu_773_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val2_2_i_reg_300 <= result_val2_6_i_reg_190;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val2_2_i_reg_300 <= newSel47_i_fu_997_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val2_6_i_reg_190 <= temp_kernel_val_0_2_reg_70;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val2_6_i_reg_190 <= newSel29_i_fu_704_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        result_val_2_i_reg_372 <= result_val_6_i_reg_256;
    end else if ((ap_ST_st6_fsm_5 == ap_CS_fsm)) begin
        result_val_2_i_reg_372 <= newSel57_i_reg_1228;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        result_val_6_i_reg_256 <= temp_kernel_val_0_0_reg_142;
    end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        result_val_6_i_reg_256 <= newSel39_i_reg_1139;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        sel_tmp38_i_reg_1073 <= sel_tmp38_i_fu_472_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        sel_tmp47_i_reg_1084 <= sel_tmp47_i_fu_490_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_460_p2 == ap_const_lv1_0))) begin
        sel_tmp50_i_reg_1092 <= sel_tmp50_i_fu_496_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        sel_tmp59_i_reg_1113 <= sel_tmp59_i_fu_548_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        sel_tmp85_i_reg_1182 <= sel_tmp85_i_fu_837_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        sel_tmp87_i_reg_1188 <= sel_tmp87_i_fu_842_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        temp_kernel_val_0_0_reg_142 <= result_val_2_i_reg_372;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        temp_kernel_val_0_1_reg_106 <= result_val16_2_i_reg_336;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        temp_kernel_val_0_2_reg_70 <= result_val2_2_i_reg_300;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        temp_kernel_val_1_0_reg_82 <= result_val13_2_i_reg_312;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        temp_kernel_val_1_1_reg_94 <= result_val14_2_i_reg_324;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        temp_kernel_val_1_2_reg_118 <= result_val1520_2_i_reg_348;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        temp_kernel_val_2_0_reg_130 <= result_val26_2_i_reg_360;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        temp_kernel_val_2_1_reg_154 <= result_val27_2_i_reg_384;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st5_fsm_4 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond5_i_fu_781_p2))) begin
        temp_kernel_val_2_2_reg_166 <= result_val28_2_i_reg_396;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_502_p2))) begin
        tmp1_i_reg_1108 <= tmp1_i_fu_542_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_ST_st7_fsm_6 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// p_dst_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_dst_data_stream_0_V_write = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_write;
    end else begin
        p_dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// p_dst_data_stream_1_V_write assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_dst_data_stream_1_V_write = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_write;
    end else begin
        p_dst_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// p_dst_data_stream_2_V_write assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_dst_data_stream_2_V_write = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_write;
    end else begin
        p_dst_data_stream_2_V_write = ap_const_logic_0;
    end
end

/// p_src_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_src_data_stream_0_V_read = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_read;
    end else begin
        p_src_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_1_V_read assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_src_data_stream_1_V_read = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_read;
    end else begin
        p_src_data_stream_1_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_2_V_read assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st7_fsm_6 == ap_CS_fsm))) begin
        p_src_data_stream_2_V_read = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_read;
    end else begin
        p_src_data_stream_2_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_57 or exitcond_fu_460_p2 or exitcond7_fu_502_p2 or exitcond5_i_fu_781_p2 or grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~ap_sig_bdd_57) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if ((exitcond_fu_460_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        ap_ST_st3_fsm_2 : 
            if (~(ap_const_lv1_0 == exitcond7_fu_502_p2)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        ap_ST_st4_fsm_3 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
        ap_ST_st5_fsm_4 : 
            if ((ap_const_lv1_0 == exitcond5_i_fu_781_p2)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        ap_ST_st6_fsm_5 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
        ap_ST_st7_fsm_6 : 
            if (~(ap_const_logic_0 == grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_57 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_57 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end
assign exitcond5_i_fu_781_p2 = (indvar_i_reg_408 == ap_const_lv32_0? 1'b1: 1'b0);
assign exitcond7_fu_502_p2 = (j_reg_289 == ap_const_lv2_3? 1'b1: 1'b0);
assign exitcond_fu_460_p2 = (i_reg_178 == ap_const_lv2_3? 1'b1: 1'b0);
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_ap_start_ap_start_reg;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_cols = p_src_cols_V_read;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_0_read = temp_kernel_val_0_0_reg_142;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_1_read = temp_kernel_val_0_1_reg_106;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_0_2_read = temp_kernel_val_0_2_reg_70;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_0_read = temp_kernel_val_1_0_reg_82;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_1_read = temp_kernel_val_1_1_reg_94;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_1_2_read = temp_kernel_val_1_2_reg_118;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_0_read = temp_kernel_val_2_0_reg_130;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_1_read = temp_kernel_val_2_1_reg_154;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_kernel_val_2_2_read = temp_kernel_val_2_2_reg_166;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_full_n = p_dst_data_stream_0_V_full_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_full_n = p_dst_data_stream_1_V_full_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_full_n = p_dst_data_stream_2_V_full_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_dout = p_src_data_stream_0_V_dout;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_0_V_empty_n = p_src_data_stream_0_V_empty_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_dout = p_src_data_stream_1_V_dout;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_1_V_empty_n = p_src_data_stream_1_V_empty_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_dout = p_src_data_stream_2_V_dout;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_src_data_stream_2_V_empty_n = p_src_data_stream_2_V_empty_n;
assign grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_rows = p_src_rows_V_read;
assign grp_fu_456_p2 = (sel_tmp38_i_reg_1073 | sel_tmp50_i_reg_1092);
assign i_2_fu_466_p2 = (i_reg_178 + ap_const_lv2_1);
assign indvar_next1_i_fu_508_p2 = (j_reg_289 + ap_const_lv2_1);
assign indvar_next_i_fu_787_p2 = (indvar_i_reg_408 + ap_const_lv32_1);
assign newSel27_i_fu_678_p3 = ((or_cond9_i_fu_665_p2)? result_val2_6_i_reg_190: newSel_i_fu_670_p3);
assign newSel28_i_fu_692_p3 = ((or_cond11_i_reg_1120)? result_val2_6_i_reg_190: newSel27_i_fu_678_p3);
assign newSel29_i_fu_704_p3 = ((or_cond13_i_fu_699_p2)? newSel28_i_fu_692_p3: result_val2_6_i_reg_190);
assign newSel30_i_fu_712_p3 = ((sel_tmp61_i_fu_657_p2)? ap_const_lv8_1: result_val14_6_i_reg_212);
assign newSel31_i_fu_720_p3 = ((or_cond11_i_reg_1120)? result_val14_6_i_reg_212: newSel30_i_fu_712_p3);
assign newSel32_i_fu_727_p3 = ((sel_tmp_i_fu_653_p2)? ap_const_lv8_1: result_val16_6_i_reg_223);
assign newSel33_i_fu_735_p3 = ((or_cond9_i_fu_665_p2)? result_val16_6_i_reg_223: newSel32_i_fu_727_p3);
assign newSel34_i_fu_743_p3 = ((or_cond11_i_reg_1120)? result_val16_6_i_reg_223: newSel33_i_fu_735_p3);
assign newSel35_i_fu_750_p3 = ((sel_tmp61_i_fu_657_p2)? result_val1520_6_i_reg_234: ap_const_lv8_1);
assign newSel36_i_fu_758_p3 = ((or_cond9_i_fu_665_p2)? newSel35_i_fu_750_p3: result_val1520_6_i_reg_234);
assign newSel37_i_fu_766_p3 = ((or_cond11_i_reg_1120)? result_val1520_6_i_reg_234: newSel36_i_fu_758_p3);
assign newSel38_i_fu_613_p3 = ((tmp_63_i_fu_565_p2)? ap_const_lv8_1: result_val_6_i_reg_256);
assign newSel39_i_fu_621_p3 = ((or_cond_i_fu_571_p2)? result_val_6_i_reg_256: newSel38_i_fu_613_p3);
assign newSel40_i_fu_629_p3 = ((tmp_63_i_fu_565_p2)? result_val27_6_i_reg_267: ap_const_lv8_1);
assign newSel41_i_fu_637_p3 = ((or_cond_i_fu_571_p2)? result_val27_6_i_reg_267: newSel40_i_fu_629_p3);
assign newSel42_i_fu_645_p3 = ((or_cond11_i_fu_583_p2)? newSel41_i_fu_637_p3: result_val27_6_i_reg_267);
assign newSel43_i_fu_773_p3 = ((or_cond13_i_fu_699_p2)? result_val28_6_i_reg_278: ap_const_lv8_1);
assign newSel44_i_fu_972_p3 = ((sel_tmp85_i_reg_1182)? result_val2_2_i_reg_300: ap_const_lv8_0);
assign newSel45_i_fu_979_p3 = ((or_cond38_i_reg_1193)? result_val2_2_i_reg_300: newSel44_i_fu_972_p3);
assign newSel46_i_fu_986_p3 = ((or_cond40_i_reg_1200)? result_val2_2_i_reg_300: newSel45_i_fu_979_p3);
assign newSel47_i_fu_997_p3 = ((or_cond42_i_fu_993_p2)? newSel46_i_fu_986_p3: result_val2_2_i_reg_300);
assign newSel48_i_fu_908_p3 = ((sel_tmp87_i_fu_842_p2)? ap_const_lv8_0: result_val14_2_i_reg_324);
assign newSel49_i_fu_916_p3 = ((or_cond40_i_fu_880_p2)? result_val14_2_i_reg_324: newSel48_i_fu_908_p3);
assign newSel50_i_fu_1005_p3 = ((sel_tmp85_i_reg_1182)? ap_const_lv8_0: result_val16_2_i_reg_336);
assign newSel51_i_fu_1012_p3 = ((or_cond38_i_reg_1193)? result_val16_2_i_reg_336: newSel50_i_fu_1005_p3);
assign newSel52_i_fu_1019_p3 = ((or_cond40_i_reg_1200)? result_val16_2_i_reg_336: newSel51_i_fu_1012_p3);
assign newSel53_i_fu_1026_p3 = ((sel_tmp87_i_reg_1188)? result_val1520_2_i_reg_348: ap_const_lv8_0);
assign newSel54_i_fu_1033_p3 = ((or_cond38_i_reg_1193)? newSel53_i_fu_1026_p3: result_val1520_2_i_reg_348);
assign newSel55_i_fu_1040_p3 = ((or_cond40_i_reg_1200)? result_val1520_2_i_reg_348: newSel54_i_fu_1033_p3);
assign newSel56_i_fu_932_p3 = ((sel_tmp89_i_fu_852_p2)? ap_const_lv8_0: result_val_2_i_reg_372);
assign newSel57_i_fu_940_p3 = ((or_cond36_i_fu_857_p2)? result_val_2_i_reg_372: newSel56_i_fu_932_p3);
assign newSel58_i_fu_948_p3 = ((sel_tmp89_i_fu_852_p2)? result_val27_2_i_reg_384: ap_const_lv8_0);
assign newSel59_i_fu_956_p3 = ((or_cond36_i_fu_857_p2)? result_val27_2_i_reg_384: newSel58_i_fu_948_p3);
assign newSel60_i_fu_964_p3 = ((or_cond40_i_fu_880_p2)? newSel59_i_fu_956_p3: result_val27_2_i_reg_384);
assign newSel61_i_fu_1047_p3 = ((or_cond42_i_fu_993_p2)? result_val28_2_i_reg_396: ap_const_lv8_0);
assign newSel_i_fu_670_p3 = ((sel_tmp_i_fu_653_p2)? result_val2_6_i_reg_190: ap_const_lv8_1);
assign or_cond11_i_fu_583_p2 = (or_cond_i_fu_571_p2 | or_cond8_i_fu_577_p2);
assign or_cond12_i_fu_686_p2 = (tmp_fu_661_p2 & grp_fu_456_p2);
assign or_cond13_i_fu_699_p2 = (or_cond11_i_reg_1120 | or_cond12_i_fu_686_p2);
assign or_cond36_i_fu_857_p2 = (sel_tmp78_i_fu_808_p2 | sel_tmp74_i_fu_803_p2);
assign or_cond37_i_fu_863_p2 = (sel_tmp89_i_fu_852_p2 | sel_tmp88_i_fu_847_p2);
assign or_cond38_i_fu_875_p2 = (sel_tmp38_i_reg_1073 & tmp3_fu_869_p2);
assign or_cond40_i_fu_880_p2 = (or_cond36_i_fu_857_p2 | or_cond37_i_fu_863_p2);
assign or_cond41_i_fu_886_p2 = (tmp3_fu_869_p2 & grp_fu_456_p2);
assign or_cond42_i_fu_993_p2 = (or_cond40_i_reg_1200 | or_cond41_i_reg_1208);
assign or_cond8_i_fu_577_p2 = (tmp_63_i_fu_565_p2 | sel_tmp62_i_fu_554_p2);
assign or_cond9_i_fu_665_p2 = (sel_tmp38_i_reg_1073 & tmp_fu_661_p2);
assign or_cond_i_fu_571_p2 = (sel_tmp48_i_fu_525_p2 | sel_tmp40_i_fu_520_p2);
assign p_dst_data_stream_0_V_din = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_0_V_din;
assign p_dst_data_stream_1_V_din = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_1_V_din;
assign p_dst_data_stream_2_V_din = grp_filter_opr_erode_kernel_16_16_unsigned_char_int_1080_1920_3_3_s_fu_420_p_dst_data_stream_2_V_din;
assign result_val13_1_i_fu_900_p3 = ((sel_tmp78_i_fu_808_p2)? result_val13_2_i_reg_312: sel_tmp90_i_fu_892_p3);
assign result_val13_5_i_fu_597_p3 = ((sel_tmp48_i_fu_525_p2)? result_val13_6_i_reg_201: sel_tmp63_i_fu_589_p3);
assign result_val26_1_i_fu_924_p3 = ((sel_tmp78_i_fu_808_p2)? ap_const_lv8_0: result_val26_2_i_reg_360);
assign result_val26_5_i_fu_605_p3 = ((sel_tmp48_i_fu_525_p2)? ap_const_lv8_1: result_val26_6_i_reg_245);
assign sel_tmp38_i_fu_472_p2 = (i_reg_178 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp39_i_fu_514_p2 = (j_reg_289 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp40_i_fu_520_p2 = (sel_tmp38_i_reg_1073 & sel_tmp39_i_fu_514_p2);
assign sel_tmp45_i_fu_478_p2 = (i_reg_178 != ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp46_i_fu_484_p2 = (i_reg_178 != ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp47_i_fu_490_p2 = (sel_tmp45_i_fu_478_p2 & sel_tmp46_i_fu_484_p2);
assign sel_tmp48_i_fu_525_p2 = (sel_tmp47_i_reg_1084 & sel_tmp39_i_fu_514_p2);
assign sel_tmp50_i_fu_496_p2 = (i_reg_178 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp53_i_fu_530_p2 = (j_reg_289 != ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp55_i_fu_536_p2 = (j_reg_289 != ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp59_i_fu_548_p2 = (j_reg_289 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp61_i_fu_657_p2 = (sel_tmp38_i_reg_1073 & sel_tmp59_i_reg_1113);
assign sel_tmp62_i_fu_554_p2 = (sel_tmp47_i_reg_1084 & sel_tmp59_i_fu_548_p2);
assign sel_tmp63_i_fu_589_p3 = ((sel_tmp40_i_fu_520_p2)? ap_const_lv8_1: result_val13_6_i_reg_201);
assign sel_tmp73_i_fu_797_p2 = (tmp_133_fu_793_p1 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp74_i_fu_803_p2 = (sel_tmp38_i_reg_1073 & sel_tmp73_i_fu_797_p2);
assign sel_tmp78_i_fu_808_p2 = (sel_tmp47_i_reg_1084 & sel_tmp73_i_fu_797_p2);
assign sel_tmp81_i_fu_813_p2 = (tmp_133_fu_793_p1 != ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp82_i_fu_819_p2 = (tmp_133_fu_793_p1 != ap_const_lv2_2? 1'b1: 1'b0);
assign sel_tmp84_i_fu_831_p2 = (tmp_133_fu_793_p1 == ap_const_lv2_2? 1'b1: 1'b0);
assign sel_tmp85_i_fu_837_p2 = (sel_tmp50_i_reg_1092 & sel_tmp84_i_fu_831_p2);
assign sel_tmp87_i_fu_842_p2 = (sel_tmp38_i_reg_1073 & sel_tmp84_i_fu_831_p2);
assign sel_tmp88_i_fu_847_p2 = (sel_tmp47_i_reg_1084 & sel_tmp84_i_fu_831_p2);
assign sel_tmp89_i_fu_852_p2 = (sel_tmp50_i_reg_1092 & sel_tmp73_i_fu_797_p2);
assign sel_tmp90_i_fu_892_p3 = ((sel_tmp74_i_fu_803_p2)? ap_const_lv8_0: result_val13_2_i_reg_312);
assign sel_tmp_i_fu_653_p2 = (sel_tmp50_i_reg_1092 & sel_tmp59_i_reg_1113);
assign tmp1_i_fu_542_p2 = (sel_tmp53_i_fu_530_p2 & sel_tmp55_i_fu_536_p2);
assign tmp29_i_fu_825_p2 = (sel_tmp81_i_fu_813_p2 & sel_tmp82_i_fu_819_p2);
assign tmp3_fu_869_p2 = (tmp29_i_fu_825_p2 | sel_tmp84_i_fu_831_p2);
assign tmp_133_fu_793_p1 = indvar_i_reg_408[1:0];
assign tmp_62_i_fu_559_p2 = (i_reg_178 | j_reg_289);
assign tmp_63_i_fu_565_p2 = (tmp_62_i_fu_559_p2 == ap_const_lv2_0? 1'b1: 1'b0);
assign tmp_fu_661_p2 = (tmp1_i_reg_1108 | sel_tmp59_i_reg_1113);


endmodule //Erode_16_16_1080_1920_s

